kafka:
  brokers:
    - "127.0.0.1:9092"
  consumer:
    groupId: "sample-consumer"
    maxRetry: 1
    deadLetterTopic: "deadletter"
    concurrency: 1
    cron: "*/1 * * * *"
    duration: 20s
  logLevel: debug